name: "Luke Dubber: Techno jargon"
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
highlighter: pygments
image: "http://img.lukedubber.com/"
